config:
  gpus: 1
  verbose: True
  fp16_opt: NULL

  model: NULL

  trainer:
    batch_size: 128

  evaluate:
    batch_size: 128

  saver:
    output_dir: datasets/Kinetics/results/zsl_baselines/ESZSL/vid.pretsm.res50.txt.glove42b.margin.0.1

  dataset:
    num_workers: 4
    ft_dir: datasets/Kinetics/features/tsm_resnet50
    label_embed_file: datasets/Kinetics/zsl220/labels_glove42b.npy
    k_class_split: 0
    class_idxs_files: 
      trn: datasets/Kinetics/zsl220/trn_class_idxs.json
      val: datasets/Kinetics/zsl220/val_class_idxs.json
      tst: datasets/Kinetics/zsl220/tst_class_idxs.json
    name_files:
      trn: datasets/Kinetics/zsl220/trn_video_names.json
      val: datasets/Kinetics/zsl220/val_video_names.json
      tst: datasets/Kinetics/zsl220/tst_video_names.json
    meta_files:
      trn: datasets/Kinetics/zsl220/trn_video_metas.jsonl
      val: datasets/Kinetics/zsl220/val_video_metas.jsonl
      tst: datasets/Kinetics/zsl220/tst_video_metas.jsonl
    

